"""add task table

Revision ID: 7d3f9edb6177
Revises: 3ac18a7a348b
Create Date: 2026-09-10 15:22:55.554116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3f9edb6177'
down_revision: Union[str, Sequence[str], None] = '3ac18a7a348b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.String(length=1000), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('update_dt', sa.DateTime(), nullable=True),
    sa.Column('started_dt', sa.DateTime(), nullable=True),
    sa.Column('finished_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_department_id'), 'task', ['department_id'], unique=False)
    op.create_index(op.f('ix_task_document_id'), 'task', ['document_id'], unique=False)
    op.create_index(op.f('ix_task_knowledge_id'), 'task', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_knowledge_id'), table_name='task')
    op.drop_index(op.f('ix_task_document_id'), table_name='task')
    op.drop_index(op.f('ix_task_department_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
