"""init knowledge tables

Revision ID: c902137a8399
Revises: 
Create Date: 2026-09-09 23:20:26.965159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c902137a8399'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_database',
    sa.Column('knowledge_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('update_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('knowledge_id')
    )
    op.create_table('knowledge_document',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('knowledge_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('update_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_database.knowledge_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_document_knowledge_id'), ['knowledge_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_document_knowledge_id'))

    op.drop_table('knowledge_document')
    op.drop_table('knowledge_database')
    # ### end Alembic commands ###
